import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const TASK_DIR = path.join(ROOT, "data", "agent-status", "tasks");

const tasks = [
  {
    id: "codex-instagram-5000-rule",
    agent: "Codex",
    avatar: "codex-engineer",
    title: "5,000人未満ルール変更",
    category: "sales",
    status: "success",
    phase: "commit完了",
    progress: 100,
    priority: "high",
    startedAt: "2026-06-01T10:00:00+09:00",
    updatedAt: "2026-06-01T11:00:00+09:00",
    summary: "Instagram営業候補のフォロワー5,000人未満ルールを反映。commit d3c1397。",
    artifacts: ["docs/sales-targeting-rules.md", "hermes/prompts/instagram-sales-list-builder.md"],
    metrics: { changedFiles: 0 },
    nextAction: "日次候補生成で運用確認",
    safeToAct: true,
    notes: ["Google Sheets投入なし", "営業送信なし"],
  },
  {
    id: "codex-contact-email-update",
    agent: "Codex",
    avatar: "codex-engineer",
    title: "公開問い合わせメール変更",
    category: "infra",
    status: "success",
    phase: "push完了",
    progress: 100,
    priority: "normal",
    startedAt: "2026-06-01T15:00:00+09:00",
    updatedAt: "2026-06-01T16:00:00+09:00",
    summary: "公開問い合わせ先メールを更新。commit e1c8c20。",
    artifacts: ["src/lib/site.ts", "docs/reports/infra/maintenance/2026-06-01-contact-email-update.md"],
    metrics: { changedFiles: 2 },
    nextAction: "公開表示の確認",
    safeToAct: true,
    notes: ["Git author email変更なし", "認証設定変更なし"],
  },
  {
    id: "daily-sales-2026-06-02",
    agent: "Hermes",
    avatar: "sales-scout",
    title: "2026-06-02 12:00営業候補生成",
    category: "sales",
    status: "blocked",
    phase: "候補不足",
    progress: 35,
    priority: "high",
    startedAt: "2026-06-02T12:04:47+09:00",
    updatedAt: "2026-06-02T13:23:00+09:00",
    summary: "12:00ジョブは実行済みだが候補0件。緊急補完が必要。",
    artifacts: ["docs/reports/sales/daily/2026-06-02-daily-sales-candidates.md"],
    metrics: {
      targetCount: 10,
      actualCount: 0,
      aCandidates: 0,
      bCandidates: 0,
      blockedReasons: 1,
    },
    nextAction: "緊急補完モードで候補10件を再生成",
    safeToAct: false,
    notes: ["Google Sheets投入なし", "営業送信なし"],
  },
  {
    id: "zero-prevention-design-2026-06-02",
    agent: "Codex",
    avatar: "ops-monitor",
    title: "0件防止設計",
    category: "ops",
    status: "needs_review",
    phase: "設計反映",
    progress: 80,
    priority: "high",
    startedAt: "2026-06-02T13:00:00+09:00",
    updatedAt: "2026-06-02T13:40:52+09:00",
    summary: "候補0件を成功扱いしない設計を反映。人間確認待ち。",
    artifacts: ["docs/reports/infra/maintenance/2026-06-02-sales-prospect-zero-prevention-design.md"],
    metrics: { targetCount: 10, minimumUsableCount: 8 },
    nextAction: "Hermes既存タスクへ修正指示を貼る",
    safeToAct: false,
    notes: ["Sheets投入なし", "Hermesタスク変更なし"],
  },
  {
    id: "sheets-import-2026-06-02",
    agent: "System",
    avatar: "sheets-clerk",
    title: "Sheets投入",
    category: "sheets",
    status: "skipped",
    phase: "未実行",
    progress: 0,
    priority: "normal",
    startedAt: "2026-06-02T12:00:00+09:00",
    updatedAt: "2026-06-02T13:30:00+09:00",
    summary: "営業送信前のため未実行。",
    artifacts: [],
    metrics: { importedRows: 0 },
    nextAction: "人間検収後に必要なら投入",
    safeToAct: false,
    notes: ["Google Sheets投入なし", "send-prospects未実行"],
  },
];

fs.mkdirSync(TASK_DIR, { recursive: true });
for (const task of tasks) {
  fs.writeFileSync(path.join(TASK_DIR, `${task.id}.json`), `${JSON.stringify(task, null, 2)}\n`);
}
console.log(`Seeded ${tasks.length} agent status task file(s).`);
